import axios from "axios";
import { Dataset } from "../types";
import { LoanApplicant } from "../types/loan";
import { supabase } from "../supabaseClient";

// Base URL for API endpoints
//const API_BASE_URL = "/api";
const API_BASE_URL =
  import.meta.env.MODE === "development"
    ? "/api" // for local dev with Nginx proxy (Docker)
    : "https://core-service-m7so.onrender.com/api"; // for production

// Create an Axios instance with default config
const api = axios.create({
  baseURL: API_BASE_URL,
  //timeout: 10000, // 10 seconds timeout
});

// ===== REQUEST INTERCEPTOR =====
// Automatically add authentication token to requests
api.interceptors.request.use((config) => {
  const token = localStorage.getItem("token");
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

// ===== DATA SERVICE =====
export const dataService = {
  // Fetch all datasets
  async getDatasets(): Promise<Dataset[]> {
    const {
      data: { user },
      error,
    } = await supabase.auth.getUser();

    // const response = await axios.get(`/api/datasets/user/${user.id}`);

    console.log("Fetching all datasets from API");
    // const response = await api.get("/datasets?lite=true");
    const response = await api.get(`/datasets?lite=true&user_id=${user?.id}`);
    return response.data;
  },

  async getDatasetsLanding(): Promise<Dataset[]> {
    console.log("Fetching all datasets from API");
    const response = await api.get("/datasets/Landing");
    return response.data;
  },

  // Fetch a single dataset by ID
  async getDataset(id: number, redis = true): Promise<Dataset> {
    const response = await api.get(`/datasets/${id}?redis=${redis}`);
    return response.data;
  },

  // Create a new dataset (ID and createdAt are generated by backend)
  async createDataset(
    dataset: Omit<Dataset, "id" | "createdAt">
  ): Promise<Dataset> {
    const response = await api.post("/datasets", dataset);
    return response.data;
  },

  // Update an existing dataset by ID
  async updateDataset(id: number, dataset: Partial<Dataset>): Promise<Dataset> {
    const response = await api.put(`/datasets/${id}`, dataset);
    return response.data;
  },

  async updateDatasetName(id: number, name: string): Promise<Dataset> {
    const response = await api.put(`/datasets/name/${id}`, { name });
    return response.data;
  },

  // Delete a dataset by ID
  async deleteDataset(id: number): Promise<void> {
    await api.delete(`/datasets/${id}`);
  },

  // // Upload a CSV file and create a dataset from it
  // async uploadCSV(file: File): Promise<Dataset> {
  //   const formData = new FormData();
  //   formData.append("file", file);
  //   const response = await api.post("/datasets/upload/csv", formData, {
  //     headers: { "Content-Type": "multipart/form-data" },
  //   });
  //   return response.data;
  // },

  async uploadCSV(file: File): Promise<Dataset> {
    const {
      data: { user },
      error,
    } = await supabase.auth.getUser();

    if (error || !user) {
      throw new Error("User not authenticated");
    }

    const formData = new FormData();
    formData.append("file", file);
    formData.append("user_id", user.id); // ✅ Add the user_id here

    const response = await api.post("/datasets/upload/csv", formData, {
      headers: { "Content-Type": "multipart/form-data" },
    });

    return response.data;
  },

  // Generate a dataset of a specific type with options (e.g., count, name)
  async generateData(
    type: string,
    options: { count?: number; name?: string } = {}
  ): Promise<Dataset> {
    console.log(`Generating data of type: ${type} with options:`, options);
    const response = await api.post(`/datasets/generate/${type}`, options);
    return response.data;
  },

  // Perform a health check on the backend API
  async healthCheck(): Promise<{ status: string; timestamp: string }> {
    const response = await api.get("/health");
    return response.data;
  },

  // async getRecommendations(): Promise<LoanApplicant[]> {
  //   // const response = await api.get("/recommendations");
  //   const response = await axios.get("http://localhost:3002/recommendations");
  //   return response.data;
  // },
};
